# Generated by Django 3.0.8 on 2020-08-14 16:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200814_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='python_arguments',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='python_kwargs',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
