# Generated by Django 3.1.2 on 2020-12-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200814_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
